### PR TITLE
Send batched events in smoke test

### PR DESCRIPTION
**Pull request by trueleo**

### CODE REVIEW

**Comment by trueleo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by trueleo** [comment]
recheck

**Review by nitisht — CHANGES_REQUESTED** [review]
This is passing for the release `v0.5.0` - We expect that it should fail there due to the event issue we saw.

**Comment by trueleo** [comment]
> This is passing for the release `v0.5.0` - We expect that it should fail there due to the event issue we saw.

Adding check for it as a unit test on main, seems like a better place for it. To make this integration test fail on 0.5.0, I'll have to change it to send batched event before single events. 

https://github.com/parseablehq/parseable/pull/454

**Comment by nitisht** [comment]
Unit test is fine, but we need change what ever is needed here as well

**Pull request merged**
